---
name: Format

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pint:
    name: 🧹 Laravel Pint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: 🚀 Change directory to cineboo-api
        run: cd cineboo-api

      - name: 🚀 Run Laravel Pint
        uses: aglipanci/laravel-pint-action@2.4
        with:
          preset: laravel
          verboseMode: true
          testMode: true
